### PR TITLE
Fix the ObjectStorage ImportError

### PR DESCRIPTION
**Pull request by bobsonlin26**
Fix the issue #10

### CODE REVIEW

**Comment by bobsonlin26** [comment]
I have no idea why` ImportError: cannot import name 'ObjectStore'` in tests...

**Comment by jmaunon** [comment]
Hi @bobsinlin26. Quite weird. I have tested this today (see my PR)

**Comment by bobsonlin26** [comment]
I guess that the syft installed for test is not the latest version (Still use `ObjectStorage` instead of `ObjectStore`), so that I cannot import it ...

**Comment by jmaunon** [comment]
> Hi, @jmaunon.  I guess that the syft installed for test is not the latest version (Still use `ObjectStorage` instead of `ObjectStore`), so that I cannot import it ...

I still have no totally clear because syft version is 0.2.5 and tests are passing

**Comment by bobsonlin26** [comment]
> > Hi, @jmaunon.  I guess that the syft installed for test is not the latest version (Still use `ObjectStorage` instead of `ObjectStore`), so that I cannot import it ...
> 
> I still have no totally clear because syft version is 0.2.5 and tests are passing

Recently syft is refactored by this [commit](https://github.com/OpenMined/PySyft/commit/368630afaba985ee9c26cc0aadd1c56c42bb38a6)
If syft is installed from Pypi, maybe this commit is not included, so i cannot import `ObjectStore` from syft

**Comment by jmaunon** [comment]
Oooohhhhh I see, very tricky. For that reason I fixed in the requirements the version. PyGrid should try to use stable versions, if not we we will find this kind of problems all the time.

I mean, if syft 0.2.6 would be released, then the changes of that commit should be considered, but not before

**Comment by IonesioJunior** [comment]
Hello, @bobsonlin and  @jmaunon  thank you for fixing/working on it, The requirements.txt / Dockerfile were properly updated to work with the new Syft release (0.2.6). Could you update your branch and run the CI tests again?  ( This will probably  fix your PR.)

**Comment by bobsonlin26** [comment]
> Hello, @bobsonlin and @jmaunon thank you for fixing/working on it, The requirements.txt / Dockerfile were properly updated to work with the new Syft release (0.2.6). Could you update your branch and run the CI tests again? ( This will probably fix your PR.)

I've updated it 
But it seems that there're some bugs

**Comment by jmaunon** [comment]
> > Hello, @bobsonlin and @jmaunon thank you for fixing/working on it, The requirements.txt / Dockerfile were properly updated to work with the new Syft release (0.2.6). Could you update your branch and run the CI tests again? ( This will probably fix your PR.)
> 
> I've updated it
> But it seems that there're some bugs

Yes, after sync the repo I get your error
`ImportError: cannot import name 'ObjectStorage'`

**Comment by bobsonlin26** [comment]
> > Hello, @bobsonlin and @jmaunon thank you for fixing/working on it, The requirements.txt / Dockerfile were properly updated to work with the new Syft release (0.2.6). Could you update your branch and run the CI tests again? ( This will probably fix your PR.)
> 
> I've updated it
> But it seems that there're some bugs

I've found the bug and created an [issue](https://github.com/OpenMined/GridNode/issues/15) and [PR](https://github.com/OpenMined/GridNode/pull/16)

**Comment by bobsonlin26** [comment]
Hi, @IonesioJunior 
Due to there's kinda deadlock between this PR and #16 
So I'd like to Fix these problems at once
Is it okay to do this way?

**Comment by bobsonlin26** [comment]
It occurs a `can not serialize 'NodeClient' object` errror
It seems there's a problem in PySyft
I've created an [issue](https://github.com/OpenMined/PySyft/issues/3648) there

**Comment by jmaunon** [comment]
> It occurs a `can not serialize 'NodeClient' object` errror when `test_mul_shared_tensors`
> It seems there's a problem in PySyft
> I've created an [issue](https://github.com/OpenMined/PySyft/issues/3648) there

Yes, I noticed as well yesterdady and I reported via slack, but is better the way you did.
I worked a bit on it, but I am not an expert on serialization, and actually is quite weird because other operations are ok, but `matmul` throws an error

**Comment by juharris** [comment]
Thank you for this update. I was getting that ImportError when running `docker-compose up` in PyGrid. Any idea when the openmined/grid-node Docker container on Docker Hub will be updated?
